services:
  postgres:
    container_name: ps_sql
    image: postgres
    environment:
      POSTGRES_USER: nce
      POSTGRES_PASSWORD: nce
      PGDATA: var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: