services:
  postgres:
    container_name: ps_sql
    image: postgres
    environment:
      POSTGRES_USER: nce
      POSTGRES_PASSWORD: nce
      POSTGRES_DB: ncedb
      PGDATA: var/lib/postgresql/data
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: nce

volumes:
  postgres: