services:
  postgres:
    container_name: ps_sql
    image: postgres:15
    environment:
      POSTGRES_USER: nce
      POSTGRES_PASSWORD: nce
      POSTGRES_DB: ncedb
      PGDATA: var/lib/postgresql/data
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: