spring:
  application:
      name: backend
  datasource:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      default-schema: ncedb
  flyway:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    baseline-version: 0

authorization:
  token: ${AUTH_TOKEN}
