spring:
  application:
    name: backend
  datasource:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDBNAME}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    user: ${PGUSER}
    password: ${PGPASSWORD}
    baseline-on-migrate: true
    baseline-version: 0
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    redis:
      port: 6379
      host: ${REDISHOST}
      password: ${REDISPASSWORD}

vegvesen:
  api-key: ${VEGVESEN_API_KEY}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION}
    issuer: ${JWT_ISSUER}
  allowed-origins: ${ALLOWED_ORIGINS}

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    access-key-id: ${AWS_ACCESS_KEY_ID}
